import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { IItem } from '../../model/IItem';
import { fromWei } from '../../utilities/ethereumHelper';
import { RootState } from '../store';

export interface MarketplaceState {
    value: IItem[];
    status: 'idle' | 'loading' | 'failed';
  }
  
  const initialState: MarketplaceState = {
    value: [],
    status: 'idle',
  };

// Here is the async functions
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const setItemsAsync = createAsyncThunk(
    'marketplace/fetchItems',
    async (contracts:any) => {
      const { marketplaceContract, nftContract } = contracts;
      const nftTokenCount = await nftContract.tokenCount();
      
      let items:IItem[] = [];
      const itemCount = await marketplaceContract.itemCount();
      
      for (let i = 0; i < itemCount; i++) {
        const item = await marketplaceContract.items(i + 1);
        const level = await marketplaceContract.itemCountOfPurchases(item.itemId.toString());
        const totalPrice = await marketplaceContract.getTotalPrice(item.itemId.toString());
        const uri = await nftContract.tokenURI(parseInt(item.tokenId.toString()));
        const metadata = await fetch(uri).then(res => res.json());

        if (item.onSale) {
          items.push({
            itemId: item.itemId.toString(),
            nick: metadata.nick,
            team: metadata.team,
            description: metadata.description,
            image: metadata.image,
            seller: item.seller,
            totalPrice: fromWei(totalPrice.toString()),
            level: level.toString()
          });
        }
      }

      return items;
    }
  );

  export const marketplaceSlice = createSlice({
    name: 'marketplace',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      setItemList: (state, action: PayloadAction<IItem[]>) => {
        state.value = action.payload;
      },
    },
    //extraReducers: (builder) ... for the async function
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(setItemsAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(setItemsAsync.fulfilled, (state, action) => {
          state.status = 'idle';
          state.value = action.payload;
        })
        .addCase(setItemsAsync.rejected, (state) => {
          state.status = 'failed';
        });
    },
  });

export const { setItemList } = marketplaceSlice.actions;

  // The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const getAllItems = (state: RootState) => state.marketplace.value;

export default marketplaceSlice.reducer;